[project]
name = "package-f"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "package-e",
]

[tool.uv.sources]
package-e = { workspace = true }
