[project]
name = "package-c"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "package-b",
    "package-c",
]

[tool.uv.sources]
package-b = { workspace = true }
package-c = { workspace = true }
